title: MoonFit
description: Documentación técnica de la aplicación MoonFit
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
show_downloads: false
logo: img/luna.png
markdown: kramdown
